// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB05VE7a_47eS8Wi-h55nqV2WcRySe_B_k',
    appId: '1:187441334381:web:3f56b6d81f86749aa89764',
    messagingSenderId: '187441334381',
    projectId: 'samy-mynotes',
    authDomain: 'samy-mynotes.firebaseapp.com',
    storageBucket: 'samy-mynotes.appspot.com',
    measurementId: 'G-HXR2V7MDM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNSyCjaw11OWEHbE-bODXEJFYfrP92nOc',
    appId: '1:187441334381:android:f1a766a6164da0d4a89764',
    messagingSenderId: '187441334381',
    projectId: 'samy-mynotes',
    storageBucket: 'samy-mynotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD37MHfdoKWyIBHJ3pV48LozPS9p47DFc4',
    appId: '1:187441334381:ios:5e77101341dcb712a89764',
    messagingSenderId: '187441334381',
    projectId: 'samy-mynotes',
    storageBucket: 'samy-mynotes.appspot.com',
    iosBundleId: 'com.samuel.csec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD37MHfdoKWyIBHJ3pV48LozPS9p47DFc4',
    appId: '1:187441334381:ios:8b4077999ee88850a89764',
    messagingSenderId: '187441334381',
    projectId: 'samy-mynotes',
    storageBucket: 'samy-mynotes.appspot.com',
    iosBundleId: 'com.samuel.csec.RunnerTests',
  );
}
